"""
Build the RAG knowledge-base index.

The primary representation is a semantic embedding generated by
Sentence Transformers.

Model:
    all-MiniLM-L6-v2

The generated semantic embeddings are stored in:
    rag/index/embeddings.npy

The original dataset records are stored in:
    rag/index/metadata.json

A TF-IDF vectorizer is also built and saved as a lightweight fallback:
    rag/index/vectorizer.joblib

Run:
    python -m rag.build_index
"""

import glob
import json
import os

import joblib
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer


DATASETS_DIR = os.path.join(
    os.path.dirname(__file__),
    "..",
    "..",
    "datasets",
    "normalized",
)

INDEX_DIR = os.path.join(
    os.path.dirname(__file__),
    "index",
)

EMBEDDINGS_PATH = os.path.join(
    INDEX_DIR,
    "embeddings.npy",
)

MODEL_NAME = "all-MiniLM-L6-v2"


def load_all_records():
    """
    Load valid records from all normalized JSONL datasets.

    buggy_code is required because it is the common field available
    across the normalized datasets.

    If bug_description is missing, create a short description from
    the available fields instead of discarding the record.
    """

    records = []

    for path in glob.glob(os.path.join(DATASETS_DIR, "*.jsonl")):

        with open(path, "r", encoding="utf-8") as f:

            for line_num, line in enumerate(f, 1):

                line = line.strip()

                if not line:
                    continue

                try:
                    record = json.loads(line)

                    if not record.get("buggy_code"):
                        print(
                            f"[build_index] Skipping malformed record "
                            f"in {os.path.basename(path)}:{line_num} "
                            f"- missing buggy_code"
                        )
                        continue

                    if not record.get("bug_description"):
                        record["bug_description"] = _synthesize_description(
                            record
                        )

                    records.append(record)

                except json.JSONDecodeError as e:

                    print(
                        f"[build_index] Skipping invalid JSON in "
                        f"{os.path.basename(path)}:{line_num}: {e}"
                    )

    return records


def _synthesize_description(record: dict) -> str:
    """
    Create a short description when the original dataset does not
    contain a natural-language bug description.
    """

    bug_type = record.get("bug_type")
    error = record.get("error")
    language = record.get("language") or "code"

    if bug_type and error:
        return (
            f"A {bug_type.lower()} in "
            f"{language} code: {error}"
        )

    if bug_type:
        return (
            f"A {bug_type.lower()} found "
            f"in {language} code."
        )

    if error:
        return (
            f"{language} code that raises: "
            f"{error}"
        )

    return (
        f"A bug fixed in {language} code "
        f"(see the before/after code for details)."
    )


def embedding_text(record: dict) -> str:
    """
    Create the text representation used by the semantic embedding model.

    The same format should be used by retriever.py when creating the
    query text.
    """

    parts = []

    if record.get("bug_description"):
        parts.append(
            str(record["bug_description"])
        )

    if record.get("error"):
        parts.append(
            f"Error: {record['error']}"
        )

    if record.get("bug_type"):
        parts.append(
            f"Type: {record['bug_type']}"
        )

    if record.get("language"):
        parts.append(
            f"Language: {record['language']}"
        )

    if record.get("buggy_code"):
        parts.append(
            f"Code: {record['buggy_code']}"
        )

    return "\n".join(
        filter(None, parts)
    )


def build():
    """
    Build both semantic embeddings and the TF-IDF fallback index.
    """

    records = load_all_records()

    if not records:
        print(
            f"[build_index] No valid normalized dataset files found "
            f"in {DATASETS_DIR}."
        )
        return

    os.makedirs(
        INDEX_DIR,
        exist_ok=True,
    )

    print(
        f"[build_index] Loaded {len(records)} valid records."
    )

    texts = [
        embedding_text(record)
        for record in records
    ]

    # ---------------------------------------------------------
    # 1. Build semantic embeddings
    # ---------------------------------------------------------

    try:

        from sentence_transformers import SentenceTransformer

        print(
            f"[build_index] Loading semantic embedding model: "
            f"{MODEL_NAME}"
        )

        model = SentenceTransformer(
            MODEL_NAME
        )

        print(
            "[build_index] Generating semantic embeddings..."
        )

        embeddings = model.encode(
            texts,
            convert_to_numpy=True,
            normalize_embeddings=True,
            show_progress_bar=True,
        )

        embeddings = embeddings.astype(
            "float32"
        )

        np.save(
            EMBEDDINGS_PATH,
            embeddings,
        )

        print(
            f"[build_index] Semantic embeddings saved: "
            f"{EMBEDDINGS_PATH}"
        )

        print(
            f"[build_index] Embedding shape: "
            f"{embeddings.shape}"
        )

    except Exception as e:

        print(
            f"[build_index] WARNING: Semantic embedding "
            f"generation failed: {e}"
        )

        print(
            "[build_index] The TF-IDF fallback will still be built."
        )

    # ---------------------------------------------------------
    # 2. Build TF-IDF fallback
    # ---------------------------------------------------------

    try:

        print(
            "[build_index] Building TF-IDF fallback..."
        )

        vectorizer = TfidfVectorizer(
            max_features=5000,
            stop_words="english",
        )

        vectorizer.fit(texts)

        vectorizer_path = os.path.join(
            INDEX_DIR,
            "vectorizer.joblib",
        )

        joblib.dump(
            vectorizer,
            vectorizer_path,
        )

        print(
            f"[build_index] TF-IDF vectorizer saved: "
            f"{vectorizer_path}"
        )

    except Exception as e:

        print(
            f"[build_index] WARNING: TF-IDF build failed: {e}"
        )

    # ---------------------------------------------------------
    # 3. Save metadata
    # ---------------------------------------------------------

    try:

        metadata_path = os.path.join(
            INDEX_DIR,
            "metadata.json",
        )

        with open(
            metadata_path,
            "w",
            encoding="utf-8",
        ) as f:

            json.dump(
                records,
                f,
                ensure_ascii=False,
            )

        print(
            f"[build_index] Metadata saved: "
            f"{metadata_path}"
        )

    except Exception as e:

        print(
            f"[build_index] Failed to save metadata: {e}"
        )
        return

    # ---------------------------------------------------------
    # 4. Final status
    # ---------------------------------------------------------

    print(
        "\n[build_index] =================================="
    )

    print(
        "[build_index] INDEX BUILD COMPLETE"
    )

    print(
        f"[build_index] Total records: {len(records)}"
    )

    if os.path.exists(EMBEDDINGS_PATH):

        print(
            "[build_index] Semantic embeddings: READY"
        )

    else:

        print(
            "[build_index] Semantic embeddings: NOT AVAILABLE"
        )

    print(
        "[build_index] =================================="
    )


if __name__ == "__main__":
    build()
